# This is a config for E2B sandbox template.
# You can use template ID (o5ifmvgbe9xqaad0cljz) or template name (nextjs-demo-1274) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("nextjs-demo-1274") # Sync sandbox
# sandbox = await AsyncSandbox.create("nextjs-demo-1274") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('nextjs-demo-1274')

team_id = "8b6153c9-6991-4934-bae5-1475c33478ea"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "nextjs-demo-1274"
template_id = "o5ifmvgbe9xqaad0cljz"
